
services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: postgres
    ports:
      - "5432:5432"     
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    volumes:
      - pgdata:/var/lib/postgresql/data # store data in persistent database
      - ./docker/postgres:/docker-entrypoint-initdb.d # connect to init.sql

  frontend:
    build:
      context: . # let Docker access everything for building image
      dockerfile: frontend/kepler/Dockerfile
    container_name: frontend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://user:pass@postgres:5432/db
    volumes:
      - .:/app # temp for faster dev
    ports:
      - "8501:8501" # expose port to reach from browser

volumes:
  pgdata: