
bike_infrastructure:
  type: categorical
  mapping:
    separated_track: 1.0
    painted_bike_lane: 0.7
    shared_bike_lane: 0.4
    none: 0.0
  description: 'Bike lane type'

slope:
  type: continuous
  bins:
    - max: 3
      metrics: 1.0
    - max: 6
      metrics: 0.7
    - max: 10
      metrics: 0.4
    - max: 100
      metrics: 0.1
  description: 'Slope percentage'

maxspeed:
  type: continuous
  bins:
    - max: 30
      metrics: 1.0
    - max: 50
      metrics: 0.7
    - max: 70
      metrics: 0.4
    - max: 200
      metrics: 0.1
  description: 'Maximum traffic speed'

surface:
  type: categorical
  mapping:
    asphalt: 1.0
    concrete: 1.0
    gravel: 0.4
    sand: 0.1
  description: 'Surface type'

lighting:
  type: categorical
  mapping:
    yes: 1.0
    no: 0.5
    unknown: 0.5