
version: '1.0.0'

bike_infrastructure:
  type: categorical
  mapping:
    track: 1.0
    lane: 0.7
    footway: 0.6
    share_busway: 0.4
    share_lane: 0.4
    none: 0.0
  description: 'Bike lane type'

maxspeed:
  type: continuous
  bins:
    - max: 30
      metrics: 1.0
    - max: 50
      metrics: 0.7
    - max: 70
      metrics: 0.4
    - max: 200
      metrics: 0.1
  description: 'Maximum traffic speed'

surface:
    # Full categorical list: https://wiki.openstreetmap.org/wiki/Key:surface
  type: categorical
  mapping:
    # --- Fully paved ---
    paved: 1.0
    asphalt: 1.0
    chipseal: 0.95
    concrete: 1.0
    concrete:lanes: 1.0
    concrete:plates: 0.95
    metal: 0.95
    tiles: 0.95
    acrylic: 0.95
    tartan: 0.95

    # --- Paved but with presence of textures ---
    paving_stones: 0.8
    paving_stones:lanes: 0.8
    sett: 0.75
    cobblestone: 0.7
    bricks: 0.75
    grass_paver: 0.7
    metal_grid: 0.7
    fibre_reinforced_polymer_grate: 0.7
    unhewn_cobblestone: 0.65

    # --- Unpaved and compacted ---
    unpaved: 0.5
    compacted: 0.6
    fine_gravel: 0.6
    gravel: 0.45
    shells: 0.45
    rock: 0.4
    pebblestone: 0.4
    clay: 0.4

    # --- Natural ground ---
    ground: 0.35
    dirt: 0.35
    earth: 0.35
    grass: 0.3
    artificial_turf: 0.6
    woodchips: 0.25
    sand: 0.2
    mud: 0.15

    # --- Special  ---
    wood: 0.75
    stepping_stones: 0.6
    rubber: 0.9
    carpet: 0.85
    plastic: 0.85

    # --- Seasonal / extreme ---
    snow: 0.1
    ice: 0.05
    salt: 0.2

    # --- Unknown ---
    unknown: 0.5

  description: "Normalized surface quality score"

lighting:
  type: categorical
  mapping:
    "yes": 1.0
    "no": 0.5
    "unknown": 0.5

oneway:
  type: categorical
  mapping:
    "no": 1.0
    "yes": 0.5